import { Currency, InvestmentEnum, UpgradeType } from '../Types'

export default {
	angelScale: 7.5,
	hasMegaTickets: true,
	ignorePlatinumBoost: false,
	investments: [
		{ name: "Happy Saplings", startingNumber: 1, cost: 0.1068, power: 1.03, profit: 0.06, speed: 8 },
		{ name: "Silver-ish Bells", startingNumber: 0, cost: 10000, power: 1.05, profit: 6172, speed: 16 },
		{ name: "BB Blasters", startingNumber: 0, cost: 1000000000, power: 1.07, profit: 123401000, speed: 24 },
		{ name: "Garnish Varnish", startingNumber: 0, cost: 10000000000000, power: 1.09, profit: 1846290000000, speed: 32 },
		{ name: "Decorammunitions", startingNumber: 0, cost: 100000000000000000, power: 1.12, profit: 24130200000000000, speed: 40 },
		{ name: "Giving Tanks", startingNumber: 0, cost: 1e+22, power: 1.15, profit: 2525250000000000000, speed: 48 },
		{ name: "Fuzzees", startingNumber: 0, cost: 1e+27, power: 1.18, profit: 3.14203e+22, speed: 56 },
		{ name: "Super Bro Dolls", startingNumber: 0, cost: 1e+32, power: 1.21, profit: 3.70926e+25, speed: 64 },
		{ name: "Roast Beast", startingNumber: 0, cost: 1e+39, power: 1.25, profit: 4.32225e+29, speed: 80 }
	],
	unlocks: [
		[
			{ investment: 0, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Speed, amount: 2, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 3, cost: { price: 900, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 4, cost: { price: 1300, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 1800, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 2400, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 7, cost: { price: 3100, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 8, cost: { price: 4000, currency: Currency.Levels } }
		],
		[
			{ investment: 1, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Speed, amount: 2, cost: { price: 900, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 3, cost: { price: 1300, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 4, cost: { price: 1800, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 5, cost: { price: 2400, currency: Currency.Levels } }
		],
		[
			{ investment: 2, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Speed, amount: 2, cost: { price: 900, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 3, cost: { price: 1300, currency: Currency.Levels } }
		],
		[
			{ investment: 3, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Speed, amount: 2, cost: { price: 900, currency: Currency.Levels } }
		],
		[
			{ investment: 4, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Speed, amount: 2, cost: { price: 900, currency: Currency.Levels } }
		],
		[
			{ investment: 5, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Speed, amount: 2, cost: { price: 600, currency: Currency.Levels } }
		],
		[
			{ investment: 6, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Speed, amount: 2, cost: { price: 450, currency: Currency.Levels } }
		],
		[
			{ investment: 7, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Speed, amount: 2, cost: { price: 300, currency: Currency.Levels } }
		],
		[
			{ investment: 8, type: UpgradeType.Profit, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Speed, amount: 2, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Speed, amount: 2, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 2, cost: { price: 150, currency: Currency.Levels } }
		],
		[]
	],
	cashUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 500, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 555, cost: { price: 50000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 55, cost: { price: 50000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 555, cost: { price: 500000000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 555, cost: { price: 1000000000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 55, cost: { price: 5000000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 50000000000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 5, cost: { price: 500000000000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 55, cost: { price: 50000000000000000, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 5, cost: { price: 100000000000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 55, cost: { price: 1000000000000000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 55, cost: { price: 100000000000000000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+22, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+23, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 5, cost: { price: 1e+23, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+24, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+26, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 5, cost: { price: 5e+26, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+28, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+28, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 5, cost: { price: 1e+29, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 5e+29, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 5, cost: { price: 1e+31, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+31, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 5, cost: { price: 1e+32, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+33, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+34, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 5, cost: { price: 5e+34, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+35, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+37, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+38, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+39, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 5, cost: { price: 5e+40, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+41, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+42, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 5, cost: { price: 1e+43, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+46, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+47, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 5, cost: { price: 5e+47, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+49, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+49, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 5, cost: { price: 1e+50, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+50, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 55, cost: { price: 1e+51, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 5e+51, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 7.7777e+52, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+62, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+69, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+74, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+79, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+85, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+92, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+97, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+104, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+113, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 777, cost: { price: 5e+117, currency: Currency.Cash } }
	],
	angelUpgrades: [
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 3, cost: { price: 1e+21, currency: Currency.Angels } }
	],
	managerUpgrades: []
}