import { Currency, InvestmentEnum, UpgradeType } from '../Types'

export default {
	angelScale: 150,
	hasMegaTickets: true,
	ignorePlatinumBoost: true,
	investments: [
		{ name: "Texas Raisins", startingNumber: 1, cost: 6, power: 1.02, profit: 0.75, speed: 2 },
		{ name: "Dandy Candy", startingNumber: 0, cost: 71, power: 1.04, profit: 20, speed: 5 },
		{ name: "Ice Screams", startingNumber: 0, cost: 640, power: 1.08, profit: 180, speed: 9 },
		{ name: "Snack O'Lanterns", startingNumber: 0, cost: 20680, power: 1.16, profit: 1440, speed: 14 },
		{ name: "Shredded Treat", startingNumber: 0, cost: 344160, power: 1.32, profit: 17280, speed: 20 },
		{ name: "Creepy Dollies", startingNumber: 0, cost: 1492920, power: 1.64, profit: 207360, speed: 56 },
		{ name: "Korn Maizes", startingNumber: 0, cost: 89133040, power: 2.28, profit: 2488325, speed: 84 },
		{ name: "Brains", startingNumber: 0, cost: 149084800, power: 3.56, profit: 29860000, speed: 144 },
		{ name: "Treat Baskets", startingNumber: 0, cost: 5758901760, power: 6.12, profit: 358318000, speed: 328 },
		{ name: "Full Sized Choco-Bar", startingNumber: 0, cost: 66666666666, power: 12.24, profit: 6666500000, speed: 666 }
	],
	unlocks: [
		[
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 111, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 1111, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 2222, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 3333, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 4444, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 5555, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 6666, currency: Currency.Levels } }
		],
		[
			{ investment: 1, type: UpgradeType.Profit, amount: 66, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 66, cost: { price: 750, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 666, cost: { price: 1500, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 666, cost: { price: 3000, currency: Currency.Levels } }
		],
		[
			{ investment: 2, type: UpgradeType.Profit, amount: 66, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 666, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 666, cost: { price: 1200, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 666, cost: { price: 1800, currency: Currency.Levels } }
		],
		[
			{ investment: 3, type: UpgradeType.Profit, amount: 66, cost: { price: 50, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 666, cost: { price: 200, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 666, cost: { price: 500, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 66, cost: { price: 1000, currency: Currency.Levels } }
		],
		[
			{ investment: 4, type: UpgradeType.Profit, amount: 66, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 66, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 666, cost: { price: 250, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 66, cost: { price: 500, currency: Currency.Levels } }
		],
		[
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 15, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 150, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 666, cost: { price: 300, currency: Currency.Levels } }
		],
		[
			{ investment: 6, type: UpgradeType.Profit, amount: 66, cost: { price: 10, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 66, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 66, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 66, cost: { price: 125, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 666, cost: { price: 175, currency: Currency.Levels } }
		],
		[
			{ investment: 7, type: UpgradeType.Profit, amount: 66, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 66, cost: { price: 30, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 66, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 666, cost: { price: 120, currency: Currency.Levels } }
		],
		[
			{ investment: 8, type: UpgradeType.Profit, amount: 66, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 66, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 66, cost: { price: 50, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 666, cost: { price: 75, currency: Currency.Levels } }
		],
		[
			{ investment: 9, type: UpgradeType.Profit, amount: 66, cost: { price: 3, currency: Currency.Levels } },
			{ investment: 9, type: UpgradeType.Profit, amount: 66, cost: { price: 18, currency: Currency.Levels } },
			{ investment: 9, type: UpgradeType.Profit, amount: 66, cost: { price: 32, currency: Currency.Levels } },
			{ investment: 9, type: UpgradeType.Profit, amount: 666, cost: { price: 50, currency: Currency.Levels } }
		],
		[
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 5, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 10, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 15, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 35, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 45, currency: Currency.Levels } }
		]
	],
	cashUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 333333, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 999999, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 3333333, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 9999999, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 333333333, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 999999999, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 33333000000, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 99999000000, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 3333000000000, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 6, cost: { price: 9999000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 66666000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 600000000000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 1200000000000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 2400000000000000, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 4800000000000000, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 9600000000000000, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 22200000000000000, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 44400000000000000, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 66600000000000000, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 500000000000000000, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 6, cost: { price: 2500000000000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 10000000000000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 6.66e+22, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 9.99e+22, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 2e+23, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 8e+23, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 3.2e+24, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 8.8e+24, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 1.51e+25, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 3.25e+25, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 5.67e+25, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 6, cost: { price: 7.5e+25, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+26, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 4e+29, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 1.6e+30, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 6.4e+30, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 1.28e+31, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 2.5e+31, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 5e+31, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 8.88e+31, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 3e+32, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 2e+33, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 6, cost: { price: 1e+34, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 6.66666e+35, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 1e+36, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 2e+36, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 3e+36, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 4e+36, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 5e+36, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 6e+36, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 7e+36, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 8e+36, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 9e+36, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 6, cost: { price: 1e+37, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+38, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 3.33e+39, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 6.66e+39, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 9.99e+39, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 2.4e+40, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 4.8e+40, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 6.4e+40, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 1.28e+41, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 2e+41, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 3.55e+41, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 6, cost: { price: 5e+41, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+42, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 66, cost: { price: 6.666e+45, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 66, cost: { price: 6.6666e+46, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 66, cost: { price: 6.66666e+47, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 66, cost: { price: 6.666e+48, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 66, cost: { price: 6.6666e+49, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 6.66666e+50, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 66, cost: { price: 6.666e+51, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 66, cost: { price: 6.6666e+52, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 66, cost: { price: 6.66666e+53, currency: Currency.Cash } },
		{ investment: 9, type: UpgradeType.Profit, amount: 66, cost: { price: 6.666e+54, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 6.6666e+55, currency: Currency.Cash } }
	],
	angelUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 777, cost: { price: 777777, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.Profit, amount: 777, cost: { price: 7000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.Profit, amount: 777, cost: { price: 77000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.Profit, amount: 777, cost: { price: 777000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.Profit, amount: 777, cost: { price: 7000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.Profit, amount: 777, cost: { price: 77000000000, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.Profit, amount: 777, cost: { price: 777000000000, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.Profit, amount: 777, cost: { price: 7000000000000, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.Profit, amount: 777, cost: { price: 77000000000000, currency: Currency.Angels } },
		{ investment: 9, type: UpgradeType.Profit, amount: 777, cost: { price: 777000000000000, currency: Currency.Angels } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 7, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 0, type: UpgradeType.FreeLevels, amount: 111, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.FreeLevels, amount: 99, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.FreeLevels, amount: 88, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.FreeLevels, amount: 66, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.FreeLevels, amount: 44, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.FreeLevels, amount: 33, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.FreeLevels, amount: 22, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.FreeLevels, amount: 11, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.FreeLevels, amount: 6, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 9, type: UpgradeType.FreeLevels, amount: 2, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 0, type: UpgradeType.Profit, amount: 7, cost: { price: 77000000000000000, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.Profit, amount: 7, cost: { price: 777000000000000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.Profit, amount: 7, cost: { price: 7000000000000000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.Profit, amount: 7, cost: { price: 77000000000000000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.Profit, amount: 7, cost: { price: 777000000000000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.Profit, amount: 7, cost: { price: 7e+21, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.Profit, amount: 7, cost: { price: 7.7e+22, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.Profit, amount: 7, cost: { price: 7.77e+23, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.Profit, amount: 7, cost: { price: 7e+24, currency: Currency.Angels } },
		{ investment: 9, type: UpgradeType.Profit, amount: 7, cost: { price: 7.7e+25, currency: Currency.Angels } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 7, cost: { price: 7e+27, currency: Currency.Angels } }
	],
	managerUpgrades: []
}