import { Currency, InvestmentEnum, UpgradeType } from '../Types'

export default {
	angelScale: 150,
	hasMegaTickets: true,
	ignorePlatinumBoost: true,
	investments: [
		{ name: "Micro-Eggs", startingNumber: 1, cost: 7, power: 1.025, profit: 0.5, speed: 2 },
		{ name: "Sham-Rocks", startingNumber: 0, cost: 83, power: 1.045, profit: 10, speed: 6 },
		{ name: "Clover Fields", startingNumber: 0, cost: 749, power: 1.085, profit: 90, speed: 10 },
		{ name: "Bunny Ears", startingNumber: 0, cost: 24195, power: 1.165, profit: 720, speed: 21 },
		{ name: "Pot O' Golds", startingNumber: 0, cost: 402667, power: 1.325, profit: 8640, speed: 30 },
		{ name: "Di-egg-nostics", startingNumber: 0, cost: 98285656, power: 2.285, profit: 1244150, speed: 126 },
		{ name: "Rainbow Makers", startingNumber: 0, cost: 174429216, power: 3.565, profit: 14929000, speed: 216 },
		{ name: "Cruelty-Free Feet", startingNumber: 0, cost: 5758901760, power: 6.125, profit: 179159000, speed: 375 },
		{ name: "Yucky Charms", startingNumber: 0, cost: 33333333333, power: 12.25, profit: 7979500000, speed: 696 }
	],
	unlocks: [
		[
			{ investment: 0, type: UpgradeType.Profit, amount: 25, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 50, cost: { price: 1000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 75, cost: { price: 2000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 100, cost: { price: 3000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 125, cost: { price: 4000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 150, cost: { price: 5000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 175, cost: { price: 6000, currency: Currency.Levels } }
		],
		[
			{ investment: 1, type: UpgradeType.Profit, amount: 200, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 225, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 250, cost: { price: 1500, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 275, cost: { price: 3000, currency: Currency.Levels } }
		],
		[
			{ investment: 2, type: UpgradeType.Profit, amount: 25, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 250, cost: { price: 400, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 2500, cost: { price: 1200, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 25000, cost: { price: 1800, currency: Currency.Levels } }
		],
		[
			{ investment: 3, type: UpgradeType.Profit, amount: 25, cost: { price: 50, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 250, cost: { price: 200, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 2500, cost: { price: 500, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 25000, cost: { price: 1000, currency: Currency.Levels } }
		],
		[
			{ investment: 4, type: UpgradeType.Profit, amount: 99, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 99, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 99, cost: { price: 250, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 99, cost: { price: 500, currency: Currency.Levels } }
		],
		[
			{ investment: 5, type: UpgradeType.Profit, amount: 55, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 55, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 55, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 55, cost: { price: 125, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 555, cost: { price: 175, currency: Currency.Levels } }
		],
		[
			{ investment: 6, type: UpgradeType.Profit, amount: 55, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 55, cost: { price: 20, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 55, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 555, cost: { price: 120, currency: Currency.Levels } }
		],
		[
			{ investment: 7, type: UpgradeType.Profit, amount: 55, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 55, cost: { price: 20, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 55, cost: { price: 40, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 555, cost: { price: 80, currency: Currency.Levels } }
		],
		[
			{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 15, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 30, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 555, cost: { price: 60, currency: Currency.Levels } }
		],
		[
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 2, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 3, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 4, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 5, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 7, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 10, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 15, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 7, cost: { price: 20, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 25, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 35, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 45, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 2, cost: { price: 55, currency: Currency.Levels } }
		]
	],
	cashUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 350000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 5, cost: { price: 1000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 5, cost: { price: 2500000, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 5, cost: { price: 10000000, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 5, cost: { price: 25000000, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 5, cost: { price: 2500000000, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 5, cost: { price: 100000000000, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 5, cost: { price: 5000000000000, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 5, cost: { price: 10000000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 7, cost: { price: 50000000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 250000000000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 5, cost: { price: 1000000000000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 5, cost: { price: 2500000000000000, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 5, cost: { price: 5000000000000000, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 5, cost: { price: 10000000000000000, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 5, cost: { price: 50000000000000000, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 5, cost: { price: 75000000000000000, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 5, cost: { price: 500000000000000000, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 5, cost: { price: 2500000000000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 10000000000000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.AngelInvestor, type: UpgradeType.AngelEffectiveness, amount: 1, cost: { price: 50000000000000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 7, cost: { price: 5e+22, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 7, cost: { price: 1e+23, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 7, cost: { price: 2e+23, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 7, cost: { price: 8e+23, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 7, cost: { price: 3.2e+24, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 7, cost: { price: 1.51e+25, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 7, cost: { price: 3.25e+25, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 7, cost: { price: 5.67e+25, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 7, cost: { price: 7.5e+25, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 8, cost: { price: 1e+26, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 9, cost: { price: 4e+29, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 9, cost: { price: 1.6e+30, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 9, cost: { price: 6.4e+30, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 9, cost: { price: 1.28e+31, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 9, cost: { price: 2.5e+31, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 9, cost: { price: 8.88e+31, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 9, cost: { price: 3e+32, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 9, cost: { price: 2e+33, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+34, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 10, cost: { price: 5e+34, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 11, cost: { price: 1e+36, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 11, cost: { price: 2e+36, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 11, cost: { price: 3e+36, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 11, cost: { price: 4e+36, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 11, cost: { price: 5e+36, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 11, cost: { price: 7e+36, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 11, cost: { price: 8e+36, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 11, cost: { price: 9e+36, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 11, cost: { price: 1e+37, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 12, cost: { price: 1e+38, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 13, cost: { price: 3.33e+39, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 13, cost: { price: 6.66e+39, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 13, cost: { price: 9.99e+39, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 13, cost: { price: 2.4e+40, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 13, cost: { price: 4.8e+40, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 13, cost: { price: 1.28e+41, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 13, cost: { price: 2e+41, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 13, cost: { price: 3.55e+41, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 13, cost: { price: 5e+41, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 14, cost: { price: 1e+42, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 15, cost: { price: 5.555e+45, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 15, cost: { price: 5.5555e+46, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 15, cost: { price: 5.55555e+47, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 15, cost: { price: 5.555e+48, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 15, cost: { price: 5.5555e+49, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 15, cost: { price: 5.555e+51, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 15, cost: { price: 5.5555e+52, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 15, cost: { price: 5.55555e+53, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 15, cost: { price: 5.555e+54, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 16, cost: { price: 5.5555e+55, currency: Currency.Cash } }
	],
	angelUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 9, cost: { price: 654321, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.Profit, amount: 9, cost: { price: 7000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.Profit, amount: 9, cost: { price: 87000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.Profit, amount: 9, cost: { price: 987000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.Profit, amount: 9, cost: { price: 1000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.Profit, amount: 9, cost: { price: 121000000000, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.Profit, amount: 9, cost: { price: 1000000000000, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.Profit, amount: 9, cost: { price: 14000000000000, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.Profit, amount: 9, cost: { price: 151000000000000, currency: Currency.Angels } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 0, type: UpgradeType.FreeLevels, amount: 111, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.FreeLevels, amount: 100, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.FreeLevels, amount: 75, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.FreeLevels, amount: 50, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.FreeLevels, amount: 40, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.FreeLevels, amount: 20, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.FreeLevels, amount: 15, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.FreeLevels, amount: 10, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.FreeLevels, amount: 5, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 0, type: UpgradeType.Profit, amount: 9, cost: { price: 55000000000000000, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.Profit, amount: 9, cost: { price: 100000000000000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.Profit, amount: 9, cost: { price: 1000000000000000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.Profit, amount: 9, cost: { price: 10000000000000000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.Profit, amount: 9, cost: { price: 100000000000000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+22, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+23, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+24, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+25, currency: Currency.Angels } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 1e+27, currency: Currency.Angels } }
	],
	managerUpgrades: []
}