import { Currency, InvestmentEnum, UpgradeType } from '../Types'

export default {
	angelScale: 180,
	hasMegaTickets: true,
	ignorePlatinumBoost: true,
	investments: [
		{ name: "Pumpkin Spice Infuser", startingNumber: 1, cost: 5, power: 1.023, profit: 0.5, speed: 1.5 },
		{ name: "Touch Screen Football", startingNumber: 0, cost: 88, power: 1.046, profit: 9, speed: 5 },
		{ name: "Gravy-Go Helmet", startingNumber: 0, cost: 777, power: 1.083, profit: 81, speed: 8 },
		{ name: "Snug-xedo", startingNumber: 0, cost: 22222, power: 1.166, profit: 729, speed: 18 },
		{ name: "Small Talk Decoy", startingNumber: 0, cost: 444444, power: 1.323, profit: 7771, speed: 28 },
		{ name: "Leftover Delivery Drones", startingNumber: 0, cost: 99999999, power: 2.286, profit: 1111111, speed: 120 },
		{ name: "Fi-doo 3000", startingNumber: 0, cost: 222222222, power: 3.563, profit: 1212121, speed: 210 },
		{ name: "Leaf Thrower", startingNumber: 0, cost: 5555555555, power: 6.126, profit: 161616161, speed: 370 },
		{ name: "Turkey Multi-Tool", startingNumber: 0, cost: 33333333333, power: 12.26, profit: 8180000000, speed: 700 }
	],
	unlocks: [
		[
			{ investment: 0, type: UpgradeType.Profit, amount: 20, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 40, cost: { price: 1000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 60, cost: { price: 2000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 80, cost: { price: 3000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 100, cost: { price: 4000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 200, cost: { price: 5000, currency: Currency.Levels } },
			{ investment: 0, type: UpgradeType.Profit, amount: 300, cost: { price: 6000, currency: Currency.Levels } }
		],
		[
			{ investment: 1, type: UpgradeType.Profit, amount: 111, cost: { price: 120, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 222, cost: { price: 600, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 333, cost: { price: 1200, currency: Currency.Levels } },
			{ investment: 1, type: UpgradeType.Profit, amount: 444, cost: { price: 3000, currency: Currency.Levels } }
		],
		[
			{ investment: 2, type: UpgradeType.Profit, amount: 33, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 333, cost: { price: 360, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 3333, cost: { price: 1200, currency: Currency.Levels } },
			{ investment: 2, type: UpgradeType.Profit, amount: 33333, cost: { price: 1800, currency: Currency.Levels } }
		],
		[
			{ investment: 3, type: UpgradeType.Profit, amount: 22, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 222, cost: { price: 180, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 2222, cost: { price: 420, currency: Currency.Levels } },
			{ investment: 3, type: UpgradeType.Profit, amount: 22222, cost: { price: 900, currency: Currency.Levels } }
		],
		[
			{ investment: 4, type: UpgradeType.Profit, amount: 100, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 100, cost: { price: 100, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 100, cost: { price: 250, currency: Currency.Levels } },
			{ investment: 4, type: UpgradeType.Profit, amount: 100, cost: { price: 500, currency: Currency.Levels } }
		],
		[
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 4, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 30, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 60, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 120, currency: Currency.Levels } },
			{ investment: 5, type: UpgradeType.Profit, amount: 66, cost: { price: 180, currency: Currency.Levels } }
		],
		[
			{ investment: 6, type: UpgradeType.Profit, amount: 77, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 77, cost: { price: 25, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 77, cost: { price: 75, currency: Currency.Levels } },
			{ investment: 6, type: UpgradeType.Profit, amount: 777, cost: { price: 120, currency: Currency.Levels } }
		],
		[
			{ investment: 7, type: UpgradeType.Profit, amount: 44, cost: { price: 5, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 44, cost: { price: 15, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 44, cost: { price: 45, currency: Currency.Levels } },
			{ investment: 7, type: UpgradeType.Profit, amount: 444, cost: { price: 83, currency: Currency.Levels } }
		],
		[
			{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 3, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 15, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 55, cost: { price: 30, currency: Currency.Levels } },
			{ investment: 8, type: UpgradeType.Profit, amount: 555, cost: { price: 60, currency: Currency.Levels } }
		],
		[
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 1, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 2, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 5, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 7, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 9, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 11, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 13, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 15, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 7, cost: { price: 17, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 19, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 23, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Speed, amount: 2, cost: { price: 29, currency: Currency.Levels } },
			{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 2, cost: { price: 35, currency: Currency.Levels } }
		]
	],
	cashUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 4, cost: { price: 332500, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 4, cost: { price: 950000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 4, cost: { price: 2375000, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 4, cost: { price: 9500000, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 4, cost: { price: 23750000, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 4, cost: { price: 2375000000, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 4, cost: { price: 95000000000, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 4, cost: { price: 4750000000000, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 4, cost: { price: 9500000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 47500000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 5, cost: { price: 237500000000000, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 5, cost: { price: 950000000000000, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 5, cost: { price: 2375000000000000, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 5, cost: { price: 4750000000000000, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 5, cost: { price: 9500000000000000, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 5, cost: { price: 47500000000000000, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 5, cost: { price: 71250000000000000, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 5, cost: { price: 475000000000000000, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 5, cost: { price: 2375000000000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 9500000000000000000, currency: Currency.Cash } },
		{ investment: InvestmentEnum.AngelInvestor, type: UpgradeType.AngelEffectiveness, amount: 1, cost: { price: 47500000000000000000, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 6, cost: { price: 4.75e+22, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 6, cost: { price: 9.5e+22, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 6, cost: { price: 1.9e+23, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 6, cost: { price: 7.6e+23, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 6, cost: { price: 3.04e+24, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 6, cost: { price: 1.4345e+25, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 6, cost: { price: 3.0875e+25, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 6, cost: { price: 5.3865e+25, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 6, cost: { price: 7.125e+25, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 9.5e+25, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 9, cost: { price: 3.8e+29, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 9, cost: { price: 1.52e+30, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 9, cost: { price: 6.08e+30, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 9, cost: { price: 1.216e+31, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 9, cost: { price: 2.375e+31, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 9, cost: { price: 8.436e+31, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 9, cost: { price: 2.85e+32, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 9, cost: { price: 1.9e+33, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 9, cost: { price: 9.5e+33, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 4.75e+34, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 10, cost: { price: 9.5e+35, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 10, cost: { price: 1.9e+36, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 10, cost: { price: 2.85e+36, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 10, cost: { price: 3.8e+36, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 10, cost: { price: 4.75e+36, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 10, cost: { price: 6.65e+36, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 10, cost: { price: 7.5e+36, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 10, cost: { price: 8.55e+36, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 10, cost: { price: 9.5e+36, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 9.5e+37, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 11, cost: { price: 3.163e+39, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 11, cost: { price: 6.327e+39, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 11, cost: { price: 9.49e+39, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 11, cost: { price: 2.28e+40, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 11, cost: { price: 4.56e+40, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 11, cost: { price: 1.216e+41, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 11, cost: { price: 1.9e+41, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 11, cost: { price: 3.3725e+41, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 11, cost: { price: 4.75e+41, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 9.5e+41, currency: Currency.Cash } },
		{ investment: 0, type: UpgradeType.Profit, amount: 13, cost: { price: 5.277e+45, currency: Currency.Cash } },
		{ investment: 1, type: UpgradeType.Profit, amount: 13, cost: { price: 5.2777e+46, currency: Currency.Cash } },
		{ investment: 2, type: UpgradeType.Profit, amount: 13, cost: { price: 5.27777e+47, currency: Currency.Cash } },
		{ investment: 3, type: UpgradeType.Profit, amount: 13, cost: { price: 5.277e+48, currency: Currency.Cash } },
		{ investment: 4, type: UpgradeType.Profit, amount: 13, cost: { price: 5.2777e+49, currency: Currency.Cash } },
		{ investment: 5, type: UpgradeType.Profit, amount: 13, cost: { price: 5.277e+51, currency: Currency.Cash } },
		{ investment: 6, type: UpgradeType.Profit, amount: 13, cost: { price: 5.2777e+52, currency: Currency.Cash } },
		{ investment: 7, type: UpgradeType.Profit, amount: 13, cost: { price: 5.27777e+53, currency: Currency.Cash } },
		{ investment: 8, type: UpgradeType.Profit, amount: 13, cost: { price: 5.277e+54, currency: Currency.Cash } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 5.2777e+55, currency: Currency.Cash } }
	],
	angelUpgrades: [
		{ investment: 0, type: UpgradeType.Profit, amount: 9, cost: { price: 621605, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.Profit, amount: 9, cost: { price: 7000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.Profit, amount: 9, cost: { price: 83000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.Profit, amount: 9, cost: { price: 938000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.Profit, amount: 9, cost: { price: 1000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.Profit, amount: 9, cost: { price: 115000000000, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.Profit, amount: 9, cost: { price: 1000000000000, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.Profit, amount: 9, cost: { price: 13000000000000, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.Profit, amount: 9, cost: { price: 143000000000000, currency: Currency.Angels } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 99, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 0, type: UpgradeType.FreeLevels, amount: 111, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.FreeLevels, amount: 100, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.FreeLevels, amount: 75, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.FreeLevels, amount: 50, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.FreeLevels, amount: 40, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.FreeLevels, amount: 20, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.FreeLevels, amount: 15, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.FreeLevels, amount: 10, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.FreeLevels, amount: 5, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 0, type: UpgradeType.Profit, amount: 9, cost: { price: 52000000000000000, currency: Currency.Angels } },
		{ investment: 1, type: UpgradeType.Profit, amount: 9, cost: { price: 95000000000000000, currency: Currency.Angels } },
		{ investment: 2, type: UpgradeType.Profit, amount: 9, cost: { price: 950000000000000000, currency: Currency.Angels } },
		{ investment: 3, type: UpgradeType.Profit, amount: 9, cost: { price: 9000000000000000000, currency: Currency.Angels } },
		{ investment: 4, type: UpgradeType.Profit, amount: 9, cost: { price: 95000000000000000000, currency: Currency.Angels } },
		{ investment: 5, type: UpgradeType.Profit, amount: 9, cost: { price: 9e+21, currency: Currency.Angels } },
		{ investment: 6, type: UpgradeType.Profit, amount: 9, cost: { price: 9.5e+22, currency: Currency.Angels } },
		{ investment: 7, type: UpgradeType.Profit, amount: 9, cost: { price: 9.5e+23, currency: Currency.Angels } },
		{ investment: 8, type: UpgradeType.Profit, amount: 9, cost: { price: 9e+24, currency: Currency.Angels } },
		{ investment: InvestmentEnum.All, type: UpgradeType.Profit, amount: 9, cost: { price: 9.49e+26, currency: Currency.Angels } }
	],
	managerUpgrades: []
}